import type { AssessmentQuestion } from "@/features/assessment/types";

/**
 * 人文素養／文筆能力評量（約 48 題）。
 * 答案以通行教材／經典文本為準；用於本地難度定位，非升學測驗。
 */
export const ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  // —— 修辭辨異 (8) ——
  {
    id: "r1",
    section: "rhetoric",
    band: "critique",
    prompt: "「感時花濺淚，恨別鳥驚心」主要修辭效果最接近？",
    choices: ["誇飾數字", "移情／擬人化外物", "頂真連環", "雙關諧音"],
    answer: 1,
    explain: "花鳥承擔人的淚與驚，是移情。",
  },
  {
    id: "r2",
    section: "rhetoric",
    band: "critique",
    prompt: "「問君能有幾多愁？恰似一江春水向東流」用的是？",
    choices: ["借代", "比喻（以有形量抽象）", "反諷", "通感"],
    answer: 1,
    explain: "以江水之長寫愁之多。",
  },
  {
    id: "r3",
    section: "rhetoric",
    band: "critique",
    prompt: "「朱門酒肉臭，路有凍死骨」的核心手法是？",
    choices: ["對比並置", "反復詠歎", "設問自答", "通感"],
    answer: 0,
    explain: "富奢與凍骨並置產生控訴力。",
  },
  {
    id: "r4",
    section: "rhetoric",
    band: "critique",
    prompt: "「尋尋覓覓，冷冷清清，悽悽慘慘戚戚」主要靠什麼製造密度？",
    choices: ["疊字節奏", "典故堆疊", "對仗工整", "倒裝句法"],
    answer: 0,
    explain: "疊字連綿拖長情緒。",
  },
  {
    id: "r5",
    section: "rhetoric",
    band: "scene",
    prompt: "「大漠孤煙直，長河落日圓」寫景的特點是？",
    choices: ["以幾何線條定格風景", "以對話帶出風景", "以議論解釋風景", "以時間倒敘風景"],
    answer: 0,
    explain: "直／圓是視覺幾何。",
  },
  {
    id: "r6",
    section: "rhetoric",
    band: "critique",
    prompt: "「興，百姓苦；亡，百姓苦」屬於？",
    choices: ["層遞", "對稱／反復控訴", "譬喻", "誇飾"],
    answer: 1,
    explain: "興亡對稱，百姓皆苦。",
  },
  {
    id: "r7",
    section: "rhetoric",
    band: "critique",
    prompt: "「假作真時真亦假」較接近哪種修辭／思維？",
    choices: ["頂真", "悖論／辯證翻轉", "排比", "借代"],
    answer: 1,
    explain: "真假互噬，屬悖論式命題。",
  },
  {
    id: "r8",
    section: "rhetoric",
    band: "critique",
    prompt: "「展示，不要陳述」在寫作課裡主要反對什麼？",
    choices: ["反對所有形容詞", "用抽象說明代替可感場面", "反對對話", "反對短句"],
    answer: 1,
    explain: "要以場面細節代替空泛說明。",
  },

  // —— 詞語對照 (10) ——
  {
    id: "w1",
    section: "word_choice",
    band: "vocab",
    prompt: "寫「勉強維持的體面」，哪組詞更精準？",
    choices: ["漂亮／好看", "撐持／周旋", "開心／高興", "很多／不少"],
    answer: 1,
    explain: "撐持、周旋帶張力與社交周旋感。",
  },
  {
    id: "w2",
    section: "word_choice",
    band: "vocab",
    prompt: "寫眼神閃躲、不敢對視，較佳的是？",
    choices: ["很害怕", "目光游移，避開對視", "空白", "漂亮"],
    answer: 1,
    explain: "具體視動比抽象情緒標籤更精準。",
  },
  {
    id: "w3",
    section: "word_choice",
    band: "vocab",
    prompt: "「光影在牆上緩慢移動」比「時間過得很慢」好在哪？",
    choices: ["比較短", "把抽象時間變成可感細節", "用了成語", "比較口語"],
    answer: 1,
    explain: "具體感官細節承載時間感。",
  },
  {
    id: "w4",
    section: "word_choice",
    band: "vocab",
    prompt: "寫人物「假裝無事」的神色，較精準的是？",
    choices: ["高興", "淡然／強作鎮定", "漂亮", "普通"],
    answer: 1,
    explain: "淡然或強作鎮定寫表演性平靜。",
  },
  {
    id: "w5",
    section: "word_choice",
    band: "vocab",
    prompt: "「翕動」最適合形容？",
    choices: ["大門猛關", "嘴唇或鼻翼輕微開合", "人群暴衝", "雷聲大作"],
    answer: 1,
    explain: "翕動寫細微開合。",
  },
  {
    id: "w6",
    section: "word_choice",
    band: "vocab",
    prompt: "「逡巡」較接近？",
    choices: ["果斷前進", "遲疑徘徊", "歡快奔跑", "熟睡"],
    answer: 1,
    explain: "逡巡＝遲疑不前。",
  },
  {
    id: "w7",
    section: "word_choice",
    band: "vocab",
    prompt: "「淋漓」在文筆裡常強調？",
    choices: ["乾燥", "暢快透徹或濕透盡致", "安靜", "短暫"],
    answer: 1,
    explain: "酣暢／濕透的盡致感。",
  },
  {
    id: "w8",
    section: "word_choice",
    band: "vocab",
    prompt: "「<[／齟齬」一類詞常用於寫？",
    choices: ["天氣很好", "意見不合、關係摩擦", "風景優美", "考試分數"],
    answer: 1,
    explain: "寫齟齬、不合。",
  },
  {
    id: "w9",
    section: "word_choice",
    band: "vocab",
    prompt: "把「他很生氣」改得更有文采，較佳方向是？",
    choices: ["他非常非常生氣", "他額角青筋一跳，把杯墊摁進桌面", "他生氣極了", "他心情不好"],
    answer: 1,
    explain: "用身體與動作顯示情緒。",
  },
  {
    id: "w10",
    section: "word_choice",
    band: "vocab",
    prompt: "「氤氳」多寫？",
    choices: ["金石鏗鏘", "煙氣、水氣朦朧瀰漫", "刀劍交鋒", "數字統計"],
    answer: 1,
    explain: "煙嵐水氣的彌散。",
  },

  // —— 名句出處 (10) ——
  {
    id: "q1",
    section: "quote_source",
    band: "classical",
    prompt: "「我思故我在」通常歸屬？",
    choices: ["尼采", "笛卡兒", "康德", "黑格爾"],
    answer: 1,
    explain: "笛卡兒方法懷疑的經典結論。",
  },
  {
    id: "q2",
    section: "quote_source",
    band: "classical",
    prompt: "「上帝已死」與哪位思想家最常並提？",
    choices: ["亞里斯多德", "尼采", "洛克", "培根"],
    answer: 1,
    explain: "尼采對價值體系崩解的宣告。",
  },
  {
    id: "q3",
    section: "quote_source",
    band: "classical",
    prompt: "「形而上者謂之道，形而下者謂之器」出自？",
    choices: ["論語", "易經·繫辭", "孟子", "老子"],
    answer: 1,
    explain: "《易經·繫辭》。",
  },
  {
    id: "q4",
    section: "quote_source",
    band: "classical",
    prompt: "「道可道，非常道」出自？",
    choices: ["莊子·齊物論", "道德經", "中庸", "大學"],
    answer: 1,
    explain: "《道德經》首章。",
  },
  {
    id: "q5",
    section: "quote_source",
    band: "classical",
    prompt: "「知行合一」與誰最相關？",
    choices: ["朱熹", "王陽明", "韓非", "荀子"],
    answer: 1,
    explain: "王陽明心學要旨。",
  },
  {
    id: "q6",
    section: "quote_source",
    band: "classical",
    prompt: "「詞以境界為最上」出自？",
    choices: ["文心雕龍", "人間詞話", "詩品", "滄浪詩話"],
    answer: 1,
    explain: "王國維《人間詞話》。",
  },
  {
    id: "q7",
    section: "quote_source",
    band: "classical",
    prompt: "「師者，所以傳道受業解惑也」出自？",
    choices: ["勸學", "師說", "進學解", "原道"],
    answer: 1,
    explain: "韓愈《師說》。",
  },
  {
    id: "q8",
    section: "quote_source",
    band: "classical",
    prompt: "「從來如此，便對麼？」出自魯迅哪篇？",
    choices: ["阿Q正傳", "狂人日記", "祝福", "藥"],
    answer: 1,
    explain: "《狂人日記》。",
  },
  {
    id: "q9",
    section: "quote_source",
    band: "classical",
    prompt: "「先天下之憂而憂」出自？",
    choices: ["醉翁亭記", "岳陽樓記", "赤壁賦", "桃花源記"],
    answer: 1,
    explain: "范仲淹《岳陽樓記》。",
  },
  {
    id: "q10",
    section: "quote_source",
    band: "classical",
    prompt: "「敢於求知」（Sapere aude）與啟蒙論述相關於？",
    choices: ["尼采", "康德", "笛卡兒", "盧梭"],
    answer: 1,
    explain: "康德〈什麼是啟蒙〉。",
  },

  // —— 文言閱讀 (8) ——
  {
    id: "c1",
    section: "classical_reading",
    band: "classical",
    prompt: "「學而不思則罔，思而不學則殆」意謂？",
    choices: ["只學不思會迷惘，只思不學會危殆", "學思都無用", "只要背誦即可", "思慮過多必然成功"],
    answer: 0,
    explain: "學思必須互濟。",
  },
  {
    id: "c2",
    section: "classical_reading",
    band: "classical",
    prompt: "「青，取之於藍，而青於藍」強調？",
    choices: ["顏色很漂亮", "後學可超越前源", "藍草無用", "不要學習"],
    answer: 1,
    explain: "青出於藍的超越義。",
  },
  {
    id: "c3",
    section: "classical_reading",
    band: "classical",
    prompt: "「井蛙不可以語於海」主要說明？",
    choices: ["青蛙很可愛", "眼界受處境限制", "海不存在", "語言無用"],
    answer: 1,
    explain: "空間／視野限制認知。",
  },
  {
    id: "c4",
    section: "classical_reading",
    band: "classical",
    prompt: "「滿招損，謙受益」最貼近？",
    choices: ["自滿招損、謙虛受益", "財富越多越好", "謙虛等於懦弱", "滿與謙無差別"],
    answer: 0,
    explain: "經典修身對句。",
  },
  {
    id: "c5",
    section: "classical_reading",
    band: "classical",
    prompt: "「皮之不存，毛將安傅」比喻？",
    choices: ["皮毛都很重要所以要買皮衣", "根本若失，附麗無所依", "毛比皮重要", "無關輕重"],
    answer: 1,
    explain: "基礎喪失則附屬無從依附。",
  },
  {
    id: "c6",
    section: "classical_reading",
    band: "classical",
    prompt: "「不以物喜，不以己悲」主張？",
    choices: ["情緒完全被外物決定", "不因外物與私己而大喜大悲", "應該無情", "只准悲傷"],
    answer: 1,
    explain: "情緒主權，不役於物我。",
  },
  {
    id: "c7",
    section: "classical_reading",
    band: "classical",
    prompt: "「書不盡言，言不盡意」指出？",
    choices: ["書寫萬能", "表達層層不足", "不必說話", "意沒有價值"],
    answer: 1,
    explain: "書／言／意的落差。",
  },
  {
    id: "c8",
    section: "classical_reading",
    band: "classical",
    prompt: "「窮則變，變則通，通則久」敘事上可用來寫？",
    choices: ["永遠不要改變", "困局逼出轉折與新局", "通久等於失敗", "只寫風景"],
    answer: 1,
    explain: "窮—變—通—久的結構公式。",
  },

  // —— 評論用語 (6) ——
  {
    id: "k1",
    section: "critique_lexicon",
    band: "critique",
    prompt: "說一篇散文「氣韻生動」，主要在誇？",
    choices: ["錯字很少", "整體生氣與節奏活絡", "引用很多百科", "段落很長"],
    answer: 1,
    explain: "氣韻指生動的整體氣質。",
  },
  {
    id: "k2",
    section: "critique_lexicon",
    band: "critique",
    prompt: "批評「為文而造情」是在說作者？",
    choices: ["情感真摯後才寫", "先有文章任務再硬擠情感", "擅長抒情", "從不抒情"],
    answer: 1,
    explain: "劉勰所批：先文後情。",
  },
  {
    id: "k3",
    section: "critique_lexicon",
    band: "critique",
    prompt: "「一切景語皆情語」提醒評論者？",
    choices: ["風景描寫與情感無關", "寫景往往承載情感立場", "只能寫景不能寫情", "情語都是假的"],
    answer: 1,
    explain: "景中有情。",
  },
  {
    id: "k4",
    section: "critique_lexicon",
    band: "critique",
    prompt: "說人物「扁平」，通常指？",
    choices: ["外貌很瘦", "性格單一、缺乏層次", "篇幅很短", "用字很淺"],
    answer: 1,
    explain: "人物缺乏複雜度。",
  },
  {
    id: "k5",
    section: "critique_lexicon",
    band: "critique",
    prompt: "「間離效果」較接近？",
    choices: ["讓讀者完全沉浸不思考", "拉開距離，促使反思而非只共感", "刪除所有對話", "只要大結局"],
    answer: 1,
    explain: "打破沉浸以啟動批判距離。",
  },
  {
    id: "k6",
    section: "critique_lexicon",
    band: "critique",
    prompt: "評「套語過多」最中肯的改進是？",
    choices: ["再多背十句成語填進去", "換成具體場面與個人觀察", "全部改成英文", "刪掉標點"],
    answer: 1,
    explain: "以具體細節取代陳套。",
  },

  // —— 場面改寫判斷 (8) ——
  {
    id: "s1",
    section: "scene_rewrite",
    band: "scene",
    prompt: "原句：「她很傷心。」較佳改寫是？",
    choices: [
      "她非常非常傷心。",
      "她把未拆的信折好，又展開，指腹在戳痕上反覆摩挲。",
      "她傷心欲絕。",
      "她的心情很不好。",
    ],
    answer: 1,
    explain: "動作細節顯示傷心。",
  },
  {
    id: "s2",
    section: "scene_rewrite",
    band: "scene",
    prompt: "原句：「會議室氣氛很緊張。」較佳是？",
    choices: [
      "氣氛十分緊張。",
      "沒人碰那壺涼掉的茶；翻頁聲像被誰掐細了。",
      "大家都很緊張。",
      "緊張的氣氛充滿會議室。",
    ],
    answer: 1,
    explain: "用物與聲寫緊張。",
  },
  {
    id: "s3",
    section: "scene_rewrite",
    band: "scene",
    prompt: "寫「時間難熬」，哪句更場面？",
    choices: [
      "時間過得很慢。",
      "壁鐘每跳一次，他喉結也跟著空嚥一次。",
      "時間非常非常慢。",
      "他覺得度日如年。",
    ],
    answer: 1,
    explain: "鐘跳與吞嚥對位。",
  },
  {
    id: "s4",
    section: "scene_rewrite",
    band: "scene",
    prompt: "寫重逢的克制，較弱的是哪句？",
    choices: [
      "他叫她的名字，聲音卻在第二個字散掉。",
      "他們很高興再見面。",
      "她先伸手，又改握成拳，揣回大衣口袋。",
      "兩人同時住口，讓電梯數字自己跳。",
    ],
    answer: 1,
    explain: "「很高興」最抽象最弱。",
  },
  {
    id: "s5",
    section: "scene_rewrite",
    band: "scene",
    prompt: "「展示憤怒」時，較不建議的是？",
    choices: [
      "他說：『我很憤怒。』然後結束段落",
      "他笑了一下，把筆蓋扣到裂開",
      "回覆只剩一個句號，顯示已讀",
      "他把椅腳在磁磚上拖出短促尖聲",
    ],
    answer: 0,
    explain: "直接宣告情緒最弱。",
  },
  {
    id: "s6",
    section: "scene_rewrite",
    band: "scene",
    prompt: "雨景要避免套語，較佳是？",
    choices: ["雨下得很大很大。", "雨腳在鐵皮屋頂上密密點名。", "下着傾盆大雨。", "雨很漂亮。"],
    answer: 1,
    explain: "具體聲感與物面。",
  },
  {
    id: "s7",
    section: "scene_rewrite",
    band: "scene",
    prompt: "寫「他猶豫要不要說實話」，較場面的是？",
    choices: ["他很猶豫。", "他開口兩次，兩次都改成咳嗽。", "他猶豫不決。", "他不知道該不該說。"],
    answer: 1,
    explain: "開口與咳嗽的置換。",
  },
  {
    id: "s8",
    section: "scene_rewrite",
    band: "scene",
    prompt: "場面改寫的核心原則是？",
    choices: [
      "盡量用成語堆疊",
      "讓讀者透過感官與行動推斷情緒與關係",
      "每句都要超過四十字",
      "避免任何細節",
    ],
    answer: 1,
    explain: "可感細節驅動推斷。",
  },
];

export const ASSESSMENT_VERSION = 1;
