export type JpVocab = {
  id: string;
  word: string;
  reading: string;
  meaningZh: string;
  note?: string;
};

export type JpGrammar = {
  id: string;
  title: string;
  pattern: string;
  meaningZh: string;
  example: string;
  exampleZh: string;
};

/** Beginner seed — static, no CMS. N5-ish everyday words. */
export const BEGINNER_VOCAB: JpVocab[] = [
  // Greetings & basics
  { id: "v-watashi", word: "私", reading: "わたし", meaningZh: "我", note: "禮貌場合常用" },
  {
    id: "v-anata",
    word: "あなた",
    reading: "あなた",
    meaningZh: "你",
    note: "口語可省略，避免過度使用",
  },
  { id: "v-desu", word: "です", reading: "です", meaningZh: "是（丁寧形）" },
  { id: "v-arigatou", word: "ありがとう", reading: "ありがとう", meaningZh: "謝謝" },
  {
    id: "v-arigatou-gozaimasu",
    word: "ありがとうございます",
    reading: "ありがとうございます",
    meaningZh: "謝謝（更禮貌）",
  },
  { id: "v-sumimasen", word: "すみません", reading: "すみません", meaningZh: "對不起／勞駕" },
  { id: "v-gomen", word: "ごめん", reading: "ごめん", meaningZh: "抱歉（熟人）" },
  { id: "v-ohayou", word: "おはよう", reading: "おはよう", meaningZh: "早安（熟人）" },
  {
    id: "v-ohayou-gozaimasu",
    word: "おはようございます",
    reading: "おはようございます",
    meaningZh: "早安（禮貌）",
  },
  { id: "v-konnichiwa", word: "こんにちは", reading: "こんにちは", meaningZh: "你好（白天）" },
  { id: "v-konbanwa", word: "こんばんは", reading: "こんばんは", meaningZh: "晚安／晚上好" },
  { id: "v-sayounara", word: "さようなら", reading: "さようなら", meaningZh: "再見" },
  { id: "v-mata-ne", word: "またね", reading: "またね", meaningZh: "再見（下次見）" },
  { id: "v-hajimemashite", word: "はじめまして", reading: "はじめまして", meaningZh: "初次見面" },
  {
    id: "v-yoroshiku",
    word: "よろしくお願いします",
    reading: "よろしくおねがいします",
    meaningZh: "請多關照",
  },
  { id: "v-hai", word: "はい", reading: "はい", meaningZh: "是／好的" },
  { id: "v-iie", word: "いいえ", reading: "いいえ", meaningZh: "不是／不用" },
  { id: "v-douzo", word: "どうぞ", reading: "どうぞ", meaningZh: "請／請用" },
  { id: "v-doumo", word: "どうも", reading: "どうも", meaningZh: "謝謝／真是的（口語）" },
  { id: "v-onegaishimasu", word: "お願いします", reading: "おねがいします", meaningZh: "拜託／請" },
  { id: "v-itadakimasu", word: "いただきます", reading: "いただきます", meaningZh: "用餐前用語" },
  { id: "v-gochisousama", word: "ごちそうさま", reading: "ごちそうさま", meaningZh: "用餐後用語" },
  // People & places
  { id: "v-hito", word: "人", reading: "ひと", meaningZh: "人" },
  { id: "v-tomodachi", word: "友達", reading: "ともだち", meaningZh: "朋友" },
  { id: "v-sensei", word: "先生", reading: "せんせい", meaningZh: "老師" },
  { id: "v-gakusei", word: "学生", reading: "がくせい", meaningZh: "學生" },
  { id: "v-kazoku", word: "家族", reading: "かぞく", meaningZh: "家人" },
  { id: "v-ie", word: "家", reading: "いえ", meaningZh: "家／房子" },
  { id: "v-gakkou", word: "学校", reading: "がっこう", meaningZh: "學校" },
  { id: "v-kaisha", word: "会社", reading: "かいしゃ", meaningZh: "公司" },
  { id: "v-eki", word: "駅", reading: "えき", meaningZh: "車站" },
  { id: "v-mise", word: "店", reading: "みせ", meaningZh: "店" },
  { id: "v-resutoran", word: "レストラン", reading: "レストラン", meaningZh: "餐廳" },
  { id: "v-toilet", word: "トイレ", reading: "トイレ", meaningZh: "廁所" },
  { id: "v-nihon", word: "日本", reading: "にほん", meaningZh: "日本" },
  { id: "v-nihongo", word: "日本語", reading: "にほんご", meaningZh: "日語" },
  { id: "v-chuugoku", word: "中国", reading: "ちゅうごく", meaningZh: "中國" },
  // Everyday nouns
  { id: "v-hon", word: "本", reading: "ほん", meaningZh: "書" },
  { id: "v-mizu", word: "水", reading: "みず", meaningZh: "水" },
  { id: "v-ocha", word: "お茶", reading: "おちゃ", meaningZh: "茶" },
  { id: "v-gohan", word: "ご飯", reading: "ごはん", meaningZh: "飯／餐" },
  { id: "v-pan", word: "パン", reading: "パン", meaningZh: "麵包" },
  { id: "v-ringo", word: "りんご", reading: "りんご", meaningZh: "蘋果" },
  { id: "v-niku", word: "肉", reading: "にく", meaningZh: "肉" },
  { id: "v-sakana", word: "魚", reading: "さかな", meaningZh: "魚" },
  { id: "v-yasai", word: "野菜", reading: "やさい", meaningZh: "蔬菜" },
  { id: "v-kudamono", word: "果物", reading: "くだもの", meaningZh: "水果" },
  { id: "v-okane", word: "お金", reading: "おかね", meaningZh: "錢" },
  { id: "v-tokei", word: "時計", reading: "とけい", meaningZh: "鐘／錶" },
  { id: "v-kagi", word: "鍵", reading: "かぎ", meaningZh: "鑰匙" },
  { id: "v-denwa", word: "電話", reading: "でんわ", meaningZh: "電話" },
  { id: "v-keitai", word: "携帯", reading: "けいたい", meaningZh: "手機" },
  { id: "v-pasokon", word: "パソコン", reading: "パソコン", meaningZh: "電腦" },
  { id: "v-namae", word: "名前", reading: "なまえ", meaningZh: "名字" },
  { id: "v-jikoku", word: "時間", reading: "じかん", meaningZh: "時間" },
  { id: "v-kyou", word: "今日", reading: "きょう", meaningZh: "今天" },
  { id: "v-ashita", word: "明日", reading: "あした", meaningZh: "明天" },
  { id: "v-kinou", word: "昨日", reading: "きのう", meaningZh: "昨天" },
  { id: "v-ima", word: "今", reading: "いま", meaningZh: "現在" },
  { id: "v-asa", word: "朝", reading: "あさ", meaningZh: "早上" },
  { id: "v-hiru", word: "昼", reading: "ひる", meaningZh: "中午" },
  { id: "v-yoru", word: "夜", reading: "よる", meaningZh: "晚上" },
  // Verbs
  { id: "v-taberu", word: "食べる", reading: "たべる", meaningZh: "吃" },
  { id: "v-nomu", word: "飲む", reading: "のむ", meaningZh: "喝" },
  { id: "v-iku", word: "行く", reading: "いく", meaningZh: "去" },
  { id: "v-kuru", word: "来る", reading: "くる", meaningZh: "來" },
  { id: "v-kaeru", word: "帰る", reading: "かえる", meaningZh: "回家／回去" },
  { id: "v-miru", word: "見る", reading: "みる", meaningZh: "看" },
  { id: "v-kiku", word: "聞く", reading: "きく", meaningZh: "聽／問" },
  { id: "v-kaku", word: "書く", reading: "かく", meaningZh: "寫" },
  { id: "v-yomu", word: "読む", reading: "よむ", meaningZh: "讀" },
  { id: "v-hanasu", word: "話す", reading: "はなす", meaningZh: "說" },
  { id: "v-suru", word: "する", reading: "する", meaningZh: "做" },
  { id: "v-aru", word: "ある", reading: "ある", meaningZh: "有（無生物）" },
  { id: "v-iru", word: "いる", reading: "いる", meaningZh: "有／在（生物）" },
  { id: "v-kau", word: "買う", reading: "かう", meaningZh: "買" },
  { id: "v-uru", word: "売る", reading: "うる", meaningZh: "賣" },
  { id: "v-tsukuru", word: "作る", reading: "つくる", meaningZh: "做／製作" },
  { id: "v-neru", word: "寝る", reading: "ねる", meaningZh: "睡覺" },
  { id: "v-okiru", word: "起きる", reading: "おきる", meaningZh: "起床" },
  { id: "v-hataraku", word: "働く", reading: "はたらく", meaningZh: "工作" },
  { id: "v-benkyou", word: "勉強する", reading: "べんきょうする", meaningZh: "學習" },
  { id: "v-wakaru", word: "分かる", reading: "わかる", meaningZh: "明白" },
  { id: "v-suki", word: "好き", reading: "すき", meaningZh: "喜歡", note: "な形容詞用法" },
  { id: "v-kirai", word: "嫌い", reading: "きらい", meaningZh: "討厭" },
  // Adjectives
  { id: "v-ookii", word: "大きい", reading: "おおきい", meaningZh: "大的" },
  { id: "v-chiisai", word: "小さい", reading: "ちいさい", meaningZh: "小的" },
  { id: "v-ii", word: "いい", reading: "いい", meaningZh: "好的" },
  { id: "v-warui", word: "悪い", reading: "わるい", meaningZh: "壞的" },
  { id: "v-takai", word: "高い", reading: "たかい", meaningZh: "高的／貴的" },
  { id: "v-yasui", word: "安い", reading: "やすい", meaningZh: "便宜的" },
  { id: "v-atarashii", word: "新しい", reading: "あたらしい", meaningZh: "新的" },
  { id: "v-furui", word: "古い", reading: "ふるい", meaningZh: "舊的" },
  { id: "v-atsui", word: "暑い", reading: "あつい", meaningZh: "熱（天氣）" },
  { id: "v-samui", word: "寒い", reading: "さむい", meaningZh: "冷（天氣）" },
  { id: "v-oishii", word: "おいしい", reading: "おいしい", meaningZh: "好吃的" },
  { id: "v-tanoshii", word: "楽しい", reading: "たのしい", meaningZh: "快樂的" },
  { id: "v-muzukashii", word: "難しい", reading: "むずかしい", meaningZh: "難的" },
  { id: "v-yasashii", word: "易しい", reading: "やさしい", meaningZh: "簡單的" },
  { id: "v-kirei", word: "きれい", reading: "きれい", meaningZh: "漂亮／乾淨" },
  { id: "v-genki", word: "元気", reading: "げんき", meaningZh: "有精神／健康" },
  // Numbers & counters (common)
  { id: "v-ichi", word: "一", reading: "いち", meaningZh: "一" },
  { id: "v-ni", word: "二", reading: "に", meaningZh: "二" },
  { id: "v-san", word: "三", reading: "さん", meaningZh: "三" },
  { id: "v-yon", word: "四", reading: "よん", meaningZh: "四" },
  { id: "v-go", word: "五", reading: "ご", meaningZh: "五" },
  { id: "v-roku", word: "六", reading: "ろく", meaningZh: "六" },
  { id: "v-nana", word: "七", reading: "なな", meaningZh: "七" },
  { id: "v-hachi", word: "八", reading: "はち", meaningZh: "八" },
  { id: "v-kyuu", word: "九", reading: "きゅう", meaningZh: "九" },
  { id: "v-juu", word: "十", reading: "じゅう", meaningZh: "十" },
  { id: "v-hyaku", word: "百", reading: "ひゃく", meaningZh: "百" },
  // Particle / function practice items (fit schema as short phrases)
  {
    id: "v-wa-topic",
    word: "〜は",
    reading: "〜は",
    meaningZh: "主題助詞（讀作「わ」）",
    note: "標出話題",
  },
  {
    id: "v-ga-subject",
    word: "〜が",
    reading: "〜が",
    meaningZh: "主語／焦點助詞",
    note: "新資訊或「有…」",
  },
  {
    id: "v-wo-object",
    word: "〜を",
    reading: "〜を",
    meaningZh: "賓語助詞",
    note: "動作對象",
  },
  {
    id: "v-ni-place",
    word: "〜に",
    reading: "〜に",
    meaningZh: "目標／時間／存在處",
    note: "去某處、何時",
  },
  {
    id: "v-de-means",
    word: "〜で",
    reading: "〜で",
    meaningZh: "場所／手段",
    note: "在哪裡做、用什麼",
  },
  {
    id: "v-to-and",
    word: "〜と",
    reading: "〜と",
    meaningZh: "和／與",
    note: "並列或一起",
  },
  {
    id: "v-mo-also",
    word: "〜も",
    reading: "〜も",
    meaningZh: "也",
    note: "同樣適用",
  },
  {
    id: "v-no-of",
    word: "〜の",
    reading: "〜の",
    meaningZh: "的／所屬",
  },
  {
    id: "v-ka-question",
    word: "〜か",
    reading: "〜か",
    meaningZh: "疑問句結尾",
  },
  {
    id: "v-ne-confirm",
    word: "〜ね",
    reading: "〜ね",
    meaningZh: "確認／同感語氣",
  },
  {
    id: "v-yo-assert",
    word: "〜よ",
    reading: "〜よ",
    meaningZh: "告知／強調語氣",
  },
];

export const BEGINNER_GRAMMAR: JpGrammar[] = [
  {
    id: "g-desu",
    title: "名詞句・です",
    pattern: "N です",
    meaningZh: "表示「是…」（丁寧）",
    example: "私は学生です。",
    exampleZh: "我是學生。",
  },
  {
    id: "g-wa",
    title: "主題の「は」",
    pattern: "N は …",
    meaningZh: "標出主題（讀作「わ」）",
    example: "これは本です。",
    exampleZh: "這是書。",
  },
  {
    id: "g-no",
    title: "所有の「の」",
    pattern: "N1 の N2",
    meaningZh: "的／所屬",
    example: "私の本です。",
    exampleZh: "是我的書。",
  },
  {
    id: "g-ka",
    title: "疑問の「か」",
    pattern: "…か。",
    meaningZh: "疑問句結尾",
    example: "学生ですか。",
    exampleZh: "是學生嗎？",
  },
  {
    id: "g-masu",
    title: "動詞丁寧形・ます",
    pattern: "V-ます",
    meaningZh: "動詞的禮貌形",
    example: "本を読みます。",
    exampleZh: "讀書。",
  },
  {
    id: "g-wo",
    title: "目的語の「を」",
    pattern: "N を V",
    meaningZh: "標出動作對象",
    example: "水を飲みます。",
    exampleZh: "喝水。",
  },
  {
    id: "g-ni-iku",
    title: "行き先の「に」",
    pattern: "場所 に 行きます",
    meaningZh: "去某處",
    example: "学校に行きます。",
    exampleZh: "去學校。",
  },
  {
    id: "g-janai",
    title: "否定・じゃないです",
    pattern: "N じゃないです",
    meaningZh: "不是…（口語丁寧）",
    example: "学生じゃないです。",
    exampleZh: "不是學生。",
  },
];
